name: ai_agent_board_rules
channels:
  - conda-forge
dependencies:
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py312h927b8db_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - anyio=4.11.0=pyhcf101f3_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=25.4.0=pyh71513ae_0
  - brotli-python=1.2.0=py312h9d5906e_0
  - bzip2=1.0.8=h0ad9c76_8
  - ca-certificates=2025.10.5=h4c7d964_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312he06e257_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py312ha1a9051_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distro=1.9.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - frozenlist=1.7.0=py312hfdf67e6_0
  - greenlet=3.2.4=py312hbb81ca0_1
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.6.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jiter=0.11.1=py312hb0142fd_0
  - jsonpatch=1.33=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py312h2e8e312_2
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - krb5=1.21.3=hdf4eb48_0
  - langchain-openai=1.0.1=pyhd8ed1ab_0
  - langgraph=1.0.2=pyhd8ed1ab_0
  - langgraph-checkpoint=3.0.0=pyhcf101f3_0
  - langgraph-prebuilt=1.0.2=pyhcf101f3_0
  - langgraph-sdk=0.2.9=pyhcf101f3_0
  - langsmith=0.3.45=pyhd8ed1ab_1
  - libblas=3.9.0=38_hf2e6a31_mkl
  - libcblas=3.9.0=38_h2a3cdd5_mkl
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libhwloc=2.12.1=default_h64bd3f2_1002
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.9.0=38_hf9ab0e9_mkl
  - liblzma=5.8.1=h2466b09_2
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.50.4=hf5d6505_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.15.1=h5d26750_0
  - libxml2-16=2.15.1=h692994f_0
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.4=hfa2b4ca_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.3.0=hac47afa_454
  - multidict=6.6.3=py312h05f76fc_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.3.4=py312ha72d056_0
  - openai=1.109.1=pyhd8ed1ab_0
  - openssl=3.5.4=h725018a_0
  - orjson=3.11.4=py312hdabe01f_0
  - ormsgpack=1.11.0=py312h692108d_1
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py312h31fea79_0
  - psutil=7.1.2=py312he5662c2_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.3=pyh3cfb1c2_0
  - pydantic-core=2.41.4=py312hdabe01f_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh09c184e_7
  - python=3.12.12=h0159041_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.2.1=pyhcf101f3_0
  - python-xxhash=3.6.0=py312h99c85cd_0
  - python_abi=3.12=8_cp312
  - pywin32=311=py312h829343e_1
  - pyyaml=6.0.3=py312h05f76fc_0
  - pyzmq=27.0.2=py312h65432d7_1
  - regex=2025.10.23=py312he06e257_0
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sqlalchemy=2.0.44=py312he06e257_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=hd094cb3_0
  - tenacity=9.1.2=pyhd8ed1ab_0
  - tiktoken=0.12.0=py312h362b069_1
  - tk=8.6.13=h2c6b04d_2
  - tornado=6.5.2=py312he06e257_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.26100.0=h57928b3_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xxhash=0.8.3=hbba6f48_0
  - yaml=0.2.5=h6a83c73_3
  - yarl=1.22.0=py312h05f76fc_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstandard=0.23.0=py312he06e257_3
  - pip:
      - annotated-doc==0.0.4
      - asyncpg==0.30.0
      - cryptography==46.0.3
      - dataclasses-json==0.6.7
      - fastapi==0.121.2
      - filelock==3.20.0
      - fsspec==2025.10.0
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - langchain==1.0.5
      - langchain-classic==1.0.0
      - langchain-community==0.4.1
      - langchain-core==1.0.4
      - langchain-huggingface==1.0.1
      - langchain-postgres==0.0.16
      - langchain-text-splitters==1.0.0
      - markupsafe==3.0.3
      - marshmallow==3.26.1
      - mpmath==1.3.0
      - mypy-extensions==1.1.0
      - networkx==3.5
      - pdfminer-six==20250506
      - pdfplumber==0.11.7
      - pgvector==0.3.6
      - pillow==12.0.0
      - psycopg==3.2.12
      - psycopg-binary==3.2.12
      - psycopg-pool==3.2.7
      - psycopg2==2.9.11
      - pydantic-settings==2.11.0
      - pypdfium2==5.0.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentence-transformers==5.1.2
      - starlette==0.49.3
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.9.0
      - transformers==4.57.1
      - typing-inspect==0.9.0
      - tzdata==2025.2
      - mlflow
