name: ai_agent_board_rules
channels:
  - conda-forge
dependencies:
  - python=3.12
  - langchain
  - langgraph
  - langchain-openai
  - python-dotenv
  - ca-certificates
  - openssl
  - ipykernel
  - pandas
  - certifi
prefix: C:\Users\masv\AppData\Local\miniforge3\envs\ai_agent_board_rules
